default_stages: [commit]
default_language_version:
  python: python3.10
repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=128']
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: double-quote-string-fixer
      - id: requirements-txt-fixer

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.2
    hooks:
      - id: codespell
        exclude: main.spec

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: [
          --profile,
          black,
          --filter-files
        ]
        name: isort (python)

  - repo: https://github.com/PyCQA/autoflake
    rev: v1.7.7
    hooks:
      - id: autoflake
        name: autoflake
        entry: autoflake
        language: python
        "types": [ python ]
        require_serial: true
        args: [
            --in-place,
            --expand-star-imports,
            --remove-duplicate-keys,
            --remove-unused-variables,
          ]

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v2.3.0
    hooks:
      - id: add-trailing-comma
        args:
          - --py36-plus

  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    - id: black
      args: [
        --skip-string-normalization,
        --line-length=120,
        --target-version=py38
      ]
      exclude: ^(venv/|docs/)
      types: ['python']

  - repo: https://github.com/myint/unify
    rev: v0.5
    hooks:
      - id: unify
        args: [
          --in-place,
          --recursive,
        ]
        exclude: ^(venv/|docs/)
        types: [ 'python' ]

  # pre-commit run --all-files
  # pre-commit install
# TODO install
