<program> ::= <compound_statement> <DOT>

<compound_statement> ::= <BEGIN> <statement_list> <END>

<statement_list> ::= <statement> { <SEMI> <statement_list> }*

<statement> ::= <compound_statement>
              | <assignment_statement>
              | <empty>

<assignment_statement> ::= <variable> <ASSIGN> <expression>

<empty> ::= ''

<factor> ::= <PLUS> <factor>
           | <MINUS> <factor>
           | <INTEGER>
           | <LPAREN> <expression> <RPAREN>
           | <variable>

<expression> ::= <term> { (<PLUS> | <MINUS>) <term> }*

<term> ::= <factor> { (<MUL> | <DIV>) <factor> }*

<variable> ::= <ID>

<ID> ::= [a-zA-Z_][a-zA-Z0-9_]*

<INTEGER> ::= <digit>+

<digit> ::= '0' | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9'

<BEGIN> ::= 'BEGIN'
<END> ::= 'END'
<DOT> ::= '.'
<SEMI> ::= ';'
<ASSIGN> ::= ':='
<PLUS> ::= '+'
<MINUS> ::= '-'
<MUL> ::= '*'
<DIV> ::= 'DIV'
<LPAREN> ::= '('
<RPAREN> ::= ')'
